// Hunar & Hifazat Localized Translation Dictionary & Jobs Scout Data Generator

export const localization: { [key: string]: any } = {
  ur: {
    appName: 'ہنر اور حفاظت',
    welcomeSub: 'مزدوروں کا سمارٹ کیریئر اور سیفٹی مینیجر',
    welcomeDesc: 'پاکستان کے محنتی مزدوروں کے لیے تیار کردہ۔ محفوظ نوکریاں تلاش کریں، لائیو ریٹس چیک کریں، اور ٹھیکیداروں کی سیکیورٹی کی تصدیق کریں۔',
    startBtn: 'شروع کریں 🚀',
    selectLanguage: 'اپنی زبان منتخب کریں',
    phoneTitle: 'ای میل درج کریں',
    phoneSub: 'محفوظ ادائیگیوں اور اسکرو والٹ کے تحفظ کے لیے اپنی ای میل کی تصدیق کریں۔',
    phonePlaceholder: 'user@example.com',
    validPhoneMsg: 'درست ای میل درج ہے! آگے بڑھیں',
    invalidPhoneMsg: 'براہ کرم درست ای میل لکھیں',
    nextBtn: 'آگے بڑھیں ➡️',
    backBtn: 'واپس',
    otpTitle: 'تصدیقی کوڈ',
    otpSub: 'ہم نے آپ کے ای میل پر 4 ہندسوں کا سیکیورٹی کوڈ بھیجا ہے۔',
    otpVerified: 'کوڈ منظور! تصدیق مکمل ہو گئی ✅',
    otpError: 'غلط سیکیورٹی کوڈ! دوبارہ چیک کریں',
    otpTimer: 'دوبارہ کوڈ بھیجیں',
    setupTitle: 'پروفائل کی ترتیبات',
    setupSub: 'اپنا سمارٹ ڈیجیٹل آئی ڈی کارڈ حاصل کرنے کے لیے بنیادی تفصیلات درج کریں۔',
    nameLabel: 'آپ کا مکمل نام (اردو یا English)',
    namePlaceholder: 'مثال: ساجد مسیح',
    skillLabel: 'پیشہ ورانہ ہنر منتخب کریں',
    cityLabel: 'اپنا شہر منتخب کریں',
    createCardBtn: 'ڈیجیٹل آئی ڈی کارڈ حاصل کریں 💳',
    scoutTab: 'کام کی تلاش',
    guardianTab: 'تحفظ شیلڈ',
    economicTab: 'ہنر اور موسم',
    walletLabel: 'موبائل والٹ',
    walletSub: 'محفوظ اسکرو رقم',
    avgRateLabel: 'آج کی اوسط مزدوری',
    scamTitle: '⚠️ سیکیورٹی الرٹ (قریبی چوک)',
    scamNotice: 'ٹھیکیدار نے کام کروا کر ادائیگی سے انکار کر دیا۔ اس کا نمبر بلاک ہے، اس علاقے میں زبانی ریٹ پر کام سے گریز کریں۔',
    negotiatorTip: 'مشورہ: آج پینٹرز اور مزدوروں کی مانگ زیادہ ہے۔ اس کام کے ریٹ بڑھوائیں۔',
    negotiateBtn: 'AI سے ریٹ بڑھوائیں',
    negotiating: 'مذاکرات جاری ہیں...',
    negotiationDone: 'ریٹ منظور! (Rs. +300 اضافہ)',
    acceptBtn: 'کام قبول کریں',
    verifyEmployerTitle: 'ٹھیکیدار کا نمبر / نام چیک کریں',
    verifyEmployerSub: 'ٹھیکیدار کا نمبر لکھیں، ہمارا AI اس کے دیانتداری اسکور اور ماضی کا جائزہ لے گا۔',
    verifyBtn: 'معلومات چیک کریں',
    photoEscrowTitle: 'کام کی تصویری تصدیق (اسکرو)',
    photoEscrowSub: 'کام مکمل ہونے پر تصویر کھینچیں۔ AI خودکار طور پر ٹھیکیدار کو ادائیگی جاری کرنے کا سگنل دے گا۔',
    takePhotoBtn: '📷 کام کی تصویر اپلوڈ کریں',
    photoUploaded: '🟢 کام کی تصویر منظور شدہ (رقم محفوظ)',
    weatherTitle: 'موسم اور روزگار کی پیشگوئی',
    weatherDetail: '4 دن میں بارش کا امکان ہے جس سے آؤٹ ڈور کام 70% کم ہوگا۔ اندرونی کام یا واٹر پروفنگ سیکھیں۔',
    skillBtn: '💧 واٹر پروفنگ کا مفت سبق شروع کریں',
    tutorialsTitle: '60-سیکنڈ آسان ویڈیو اسباق',
    squadTitle: 'ہمسایہ ٹیم بلڈر (سکواڈ)',
    squadDetail: 'بڑے تجارتی یا تعمیراتی ٹھیکوں کے لیے قریبی کاریگروں کے ساتھ ٹیم بنائیں۔',
    squadBtn: '✨ سکواڈ بنائیں',
    verifiedWorker: 'تصدیق شدہ مزدور',
    trustScore: 'دیانتداری اسکور',
    idCardTitle: 'ڈیجیٹل لیبر کونسل کارڈ',
    logoutBtn: 'لاگ آؤٹ کریں 🔐',
    scanAlert: 'تصدیق جاری ہے...',
    skillsMap: {
      painter: 'رنگساز (Painter)',
      electrician: 'الیکٹریشن (Electrician)',
      plumber: 'نل ساز (Plumber)',
      carpenter: 'بڑھئی (Carpenter)',
      mason: 'راج مزدور (Mason)'
    }
  },
  en: {
    appName: 'Hunar & Hifazat',
    welcomeSub: 'AI Career & Safety Manager',
    welcomeDesc: 'Built specifically for hard-working daily-wage workers in Pakistan. Find secure jobs, verify employer ratings, and ensure secure payments.',
    startBtn: 'Get Started 🚀',
    selectLanguage: 'Select Your Language',
    phoneTitle: 'Verify Email Address',
    phoneSub: 'We will verify your email address to protect your smart wallet and ensure escrow safety.',
    phonePlaceholder: 'user@example.com',
    validPhoneMsg: 'Valid Email Address! Ready to proceed',
    invalidPhoneMsg: 'Please enter a valid email address',
    nextBtn: 'Next Step ➡️',
    backBtn: 'Back',
    otpTitle: 'Verification Code',
    otpSub: 'We have sent a 4-digit security code to your email address.',
    otpVerified: 'Code Approved! Phone Verified ✅',
    otpError: 'Incorrect code! Please try again',
    otpTimer: 'Resend Code',
    setupTitle: 'Smart Profile Setup',
    setupSub: 'Complete your profile information to issue your Pakistan Digital Labor Card.',
    nameLabel: 'Your Full Name',
    namePlaceholder: 'e.g. Sajid Masih',
    skillLabel: 'Select Your Primary Skill',
    cityLabel: 'Select Your Work Location',
    createCardBtn: 'Generate Smart ID Card 💳',
    scoutTab: 'Job Scout',
    guardianTab: 'Safety Shield',
    economicTab: 'Skill Engine',
    walletLabel: 'Mobile Wallet',
    walletSub: 'Escrow Secured Funds',
    avgRateLabel: "Today's Avg Rate",
    scamTitle: '⚠️ Safety Warning (Nearby Chowk)',
    scamNotice: 'An employer was flagged for non-payment. Mobile blocked. Avoid taking verbal-only jobs in this area.',
    negotiatorTip: 'Tip: High demand for labor today. Let your AI negotiator demand a higher wage.',
    negotiateBtn: 'Negotiate via AI',
    negotiating: 'AI Negotiating...',
    negotiationDone: 'Rate Secured! (Rs. +300 Gained)',
    acceptBtn: 'Accept Job',
    verifyEmployerTitle: 'Instant Contractor Vetting',
    verifyEmployerSub: 'Enter the contractor mobile number to run an automatic background check.',
    verifyBtn: 'Verify Contractor',
    photoEscrowTitle: 'Smart Photo Work Verification',
    photoEscrowSub: 'Snap a picture of your finished work. Our AI verifies it instantly and requests the escrow payout.',
    takePhotoBtn: '📷 Upload Work Photo',
    photoUploaded: '🟢 Work Photo Uploaded (Payment Released)',
    weatherTitle: 'Weather & Demand Engine',
    weatherDetail: 'Rain forecast in 4 days. Outdoor work demand will drop by 70%. We recommend taking interior or waterproofing jobs.',
    skillBtn: '💧 Start Waterproofing Tutorial (Free)',
    tutorialsTitle: '60-Second Skill Upgrades',
    squadTitle: 'Labor Squad Creator',
    squadDetail: 'Join forces with nearby available tradesmen to bid on larger commercial projects together.',
    squadBtn: 'Form A Local Team',
    verifiedWorker: 'Verified Worker',
    trustScore: 'Trust Score',
    idCardTitle: 'Digital Labor Council ID',
    logoutBtn: 'Log Out 🔐',
    scanAlert: 'Vetting in progress...',
    skillsMap: {
      painter: 'Professional Painter',
      electrician: 'Electrician',
      plumber: 'Plumber',
      carpenter: 'Carpenter',
      mason: 'Mason / Bricklayer'
    }
  }
};

export const getJobsForSkill = (skill: string, lang: 'ur' | 'en') => {
  switch (skill) {
    case 'electrician':
      return [
        {
          id: 1,
          title: lang === 'ur' ? 'گھر کی مکمل فٹنگ اور وائرنگ' : 'Full House Wiring & Fitting',
          employer: 'Tariq Mehmood (Model Town)',
          distance: '2.0 km',
          rate: 2500,
          confidence: '99%',
          details: lang === 'ur' ? 'تین کمرے، بورڈ اور تاریں فراہم کی جائیں گی' : '3 Rooms, wiring and DB boards provided',
          badge: lang === 'ur' ? 'بہترین موقع' : 'Best Match',
        },
        {
          id: 2,
          title: lang === 'ur' ? 'اے سی اور انورٹر فٹنگ' : 'AC & Inverter Installation',
          employer: 'Apex Tech (DHA Phase 6)',
          distance: '5.1 km',
          rate: 3200,
          confidence: '92%',
          details: lang === 'ur' ? '2 یونٹ فٹنگ، تانبے کی پائپ لائن کا کام' : '2 Unit fitting, copper piping job',
          badge: lang === 'ur' ? 'اعلی اجرت' : 'Top Rate',
        }
      ];
    case 'plumber':
      return [
        {
          id: 1,
          title: lang === 'ur' ? 'پانی کے پائپ کی لیکیج مرمت' : 'Water Pipeline Leakage Repair',
          employer: 'Rana Asif (Johar Town)',
          distance: '1.5 km',
          rate: 1800,
          confidence: '97%',
          details: lang === 'ur' ? 'کچن اور باتھ روم پائپ کی مرمت' : 'Kitchen & bathroom leakage fix',
          badge: lang === 'ur' ? 'فوری ضرورت' : 'Urgent Match',
        },
        {
          id: 2,
          title: lang === 'ur' ? 'باتھ روم سینیٹری فٹنگ' : 'Bathroom Sanitary Installation',
          employer: 'Crescent Builders (DHA Phase 3)',
          distance: '3.8 km',
          rate: 3000,
          confidence: '89%',
          details: lang === 'ur' ? 'نئے شاور سیٹ اور کموڈ فٹنگز' : 'New bathroom fixtures & shower sets',
          badge: lang === 'ur' ? 'بڑا پروجیکٹ' : 'High Budget',
        }
      ];
    case 'carpenter':
      return [
        {
          id: 1,
          title: lang === 'ur' ? 'کچن کیبنٹ اور دروازے کی مرمت' : 'Kitchen Cabinet Repair',
          employer: 'Faisal Iqbal (Cavalry Ground)',
          distance: '3.0 km',
          rate: 2200,
          confidence: '96%',
          details: lang === 'ur' ? 'کیبنٹ کے دروازے اور قبضے ٹھیک کرنا' : 'Fixing cabinet doors and hinges',
          badge: lang === 'ur' ? 'بہترین موقع' : 'Hot Match',
        },
        {
          id: 2,
          title: lang === 'ur' ? 'لکڑی کے دروازے پالش اور تالے' : 'Wooden Door Polishing & Locks',
          employer: 'Zaman Estates (Gulberg II)',
          distance: '1.2 km',
          rate: 2800,
          confidence: '94%',
          details: lang === 'ur' ? '4 دروازوں کی پالش اور تالے لگانا' : 'Polishing 4 main doors and lock installation',
          badge: lang === 'ur' ? 'فوری نقد' : 'Quick Cash',
        }
      ];
    case 'mason':
      return [
        {
          id: 1,
          title: lang === 'ur' ? 'دیوار کی چنائی (اینٹیں)' : 'Boundary Wall Bricklaying',
          employer: 'Malik Construction (Wapda Town)',
          distance: '4.2 km',
          rate: 3500,
          confidence: '95%',
          details: lang === 'ur' ? '50 فٹ لمبی چار دیواری کی چنائی' : '50ft boundary wall brick installation',
          badge: lang === 'ur' ? 'سرکاری ریٹ' : 'Standard Rate',
        },
        {
          id: 2,
          title: lang === 'ur' ? 'ماربل اور ٹائل فکسنگ' : 'Marble & Tile Floor Fixing',
          employer: 'Arshad Ali (Samanabad)',
          distance: '2.5 km',
          rate: 4000,
          confidence: '91%',
          details: lang === 'ur' ? 'کمرے کا فرش اور ماربل کٹنگ کا کام' : 'Room floor tiling & marble polishing',
          badge: lang === 'ur' ? 'بڑا کام' : 'Heavy Task',
        }
      ];
    case 'painter':
    default:
      return [
        {
          id: 1,
          title: lang === 'ur' ? 'گھر کی پینٹنگ (اندرونی)' : 'House Painting (Interior)',
          employer: 'Zahid Khan (Gulberg III)',
          distance: '1.2 km',
          rate: 1800,
          confidence: '98%',
          details: lang === 'ur' ? '3 کمرے، پینٹ اور برش فراہم کیے جائیں گے' : '3 Rooms, paint and brushes provided',
          badge: lang === 'ur' ? 'بہترین موقع' : 'Hot Match',
        },
        {
          id: 2,
          title: lang === 'ur' ? 'لکڑی کا فرنیچر پالش' : 'Wooden Furniture Polishing',
          employer: 'Kamran Builders (DHA Phase 5)',
          distance: '4.5 km',
          rate: 2200,
          confidence: '85%',
          details: lang === 'ur' ? '5 دروازے اور صوفہ سیٹ پالش کا کام' : '5 Doors and sofa set polishing',
          badge: lang === 'ur' ? 'اعلی رقم' : 'High Pay',
        },
      ];
  }
};
