"""Added Customer Profiles and JWTs

Revision ID: c404bf66af44
Revises: 6f58a6f091c0
Create Date: 2026-05-20 06:33:50.879500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c404bf66af44'
down_revision: Union[str, None] = '6f58a6f091c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('customer_phone', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('customer_email', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('customer_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'customer_name')
    op.drop_column('jobs', 'customer_email')
    op.drop_column('jobs', 'customer_phone')
    # ### end Alembic commands ###
